FactoryBot.define do
  factory :project do
    sequence(:name) { |n| "Beacon Project #{n}" }
    # api_key and ingest_key are generated by before_validation callback

    trait :with_platform do
      platform_project_id { SecureRandom.uuid }
    end
  end
end
